version: "3.8"

services:

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 25432:5432
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DBNAME}
    volumes: 
      - ./create-db.sql:/docker-entrypoint-initdb.d/create_database.sql

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 25050:80
    depends_on:
      - db

  server:
    container_name: server
    build: ./server
    command: bash -c "alembic upgrade head && python3 ./server.py"
    volumes:
      - ./server:/app
    ports:
      - 5555:5555
    depends_on:
      - db
    restart: always

  client:
    container_name: client-scheduler
    build: ./client
    command: ["python", "client-scheduler.py", "--source", "tenable"]
    volumes:
      - ./client:/app
    depends_on:
      - server
    restart: always
