"""New Migration

Revision ID: 15161ce2833d
Revises: 
Create Date: 2024-02-28 22:08:33.178820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15161ce2833d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('vip_members', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('customer_contact', sa.String(), nullable=True),
    sa.Column('technical_contact', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_id'), 'asset', ['id'], unique=False)
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('jira_ticket_id', sa.Integer(), nullable=True),
    sa.Column('output', sa.String(), nullable=True),
    sa.Column('plugin_id', sa.Integer(), nullable=True),
    sa.Column('plugin_name', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('port_number', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('solution', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('first_observed', sa.String(), nullable=True),
    sa.Column('last_seen', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_id'), 'ticket', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_id'), table_name='ticket')
    op.drop_table('ticket')
    op.drop_index(op.f('ix_asset_id'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
